# Generated by Django 5.0.6 on 2024-06-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='second_address',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
