# Generated by Django 5.0.6 on 2024-06-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_customer_second_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='customer',
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer_name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
